/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AvailableCategoryDTO from './model/AvailableCategoryDTO';
import BookingForm from './model/BookingForm';
import CreateBookingResponse from './model/CreateBookingResponse';
import LocalTime from './model/LocalTime';
import Price from './model/Price';
import PriceCurrency from './model/PriceCurrency';
import BookingRestControllerApi from './api/BookingRestControllerApi';
import CategoryRestControllerApi from './api/CategoryRestControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AvailableCategoryDTO model constructor.
     * @property {module:model/AvailableCategoryDTO}
     */
    AvailableCategoryDTO,

    /**
     * The BookingForm model constructor.
     * @property {module:model/BookingForm}
     */
    BookingForm,

    /**
     * The CreateBookingResponse model constructor.
     * @property {module:model/CreateBookingResponse}
     */
    CreateBookingResponse,

    /**
     * The LocalTime model constructor.
     * @property {module:model/LocalTime}
     */
    LocalTime,

    /**
     * The Price model constructor.
     * @property {module:model/Price}
     */
    Price,

    /**
     * The PriceCurrency model constructor.
     * @property {module:model/PriceCurrency}
     */
    PriceCurrency,

    /**
    * The BookingRestControllerApi service constructor.
    * @property {module:api/BookingRestControllerApi}
    */
    BookingRestControllerApi,

    /**
    * The CategoryRestControllerApi service constructor.
    * @property {module:api/CategoryRestControllerApi}
    */
    CategoryRestControllerApi
};
