/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BookingForm from '../model/BookingForm';
import BookingResponse from '../model/BookingResponse';

/**
* BookingRestController service.
* @module api/BookingRestControllerApi
* @version v0
*/
export default class BookingRestControllerApi {

    /**
    * Constructs a new BookingRestControllerApi. 
    * @alias module:api/BookingRestControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createBooking operation.
     * @callback module:api/BookingRestControllerApi~createBookingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BookingResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/BookingForm} bookingForm 
     * @param {module:api/BookingRestControllerApi~createBookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BookingResponse}
     */
    createBooking(bookingForm, callback) {
      let postBody = bookingForm;
      // verify the required parameter 'bookingForm' is set
      if (bookingForm === undefined || bookingForm === null) {
        throw new Error("Missing the required parameter 'bookingForm' when calling createBooking");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = BookingResponse;
      return this.apiClient.callApi(
        '/rest/bookings/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
