/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AvailableCategoryDTO from '../model/AvailableCategoryDTO';

/**
* CategoryRestController service.
* @module api/CategoryRestControllerApi
* @version v0
*/
export default class CategoryRestControllerApi {

    /**
    * Constructs a new CategoryRestControllerApi. 
    * @alias module:api/CategoryRestControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the availableCategoriesForBooking operation.
     * @callback module:api/CategoryRestControllerApi~availableCategoriesForBookingCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AvailableCategoryDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Date} arrivalDate 
     * @param {Date} departureDate 
     * @param {module:api/CategoryRestControllerApi~availableCategoriesForBookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AvailableCategoryDTO>}
     */
    availableCategoriesForBooking(arrivalDate, departureDate, callback) {
      let postBody = null;
      // verify the required parameter 'arrivalDate' is set
      if (arrivalDate === undefined || arrivalDate === null) {
        throw new Error("Missing the required parameter 'arrivalDate' when calling availableCategoriesForBooking");
      }
      // verify the required parameter 'departureDate' is set
      if (departureDate === undefined || departureDate === null) {
        throw new Error("Missing the required parameter 'departureDate' when calling availableCategoriesForBooking");
      }

      let pathParams = {
      };
      let queryParams = {
        'arrivalDate': arrivalDate,
        'departureDate': departureDate
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [AvailableCategoryDTO];
      return this.apiClient.callApi(
        '/rest/categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
